version: "2.1"
services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-mate
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - SUBFOLDER=/ #optional
      - TITLE=MNGT #optional
    volumes:
      - /path/to/data:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "2gb" #VGPU Default 1GB but 2GB better
    restart: always
